### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by fabltd** [mgergos/B-WL5M-SUBG1#1]
Hi 

I am pulling my hair out trying to get a B-WL5M-SUBG1 working with ardunio and found your post and this Git hub post.

Quesiton: 

Where did you find the reference to  PC3, PC4, PC5 for control of the internal RF Switch ? I am looking at the datasheet and I see PC5 and PC3 mentioned. They don't appear in the datasheet for the actuall MCU.  

Did you get this fully working? 

Sorry I also see a note in the code 

`  __HAL_RCC_LSEDRIVE_CONFIG(RCC_LSEDRIVE_HIGH);`	

Where did you find this in the datasheet? I think am being dumb but i cannot see it. The datasheet seems to be really lacking much description of how the radio is connected. 

This is the one I have been attempting to use `https://www.st.com/resource/en/datasheet/stm32wl5moc.pdf`

Thanks

**Comment by fabltd** [comment]
I manged to now get my code to complie. I have copied in your changes to the board I am using.

However it does not connect. I have no idea if the radio is working? 

Do you have any example code?  

I can return the modem EUI so thats a start. 

I am using the [STM32LoRaWAN](https://github.com/stm32duino/STM32LoRaWAN/tree/main) lib.

Thanks

**Comment by fabltd** [comment]
The schematic [https://www.st.com/resource/en/schematic_pack/mb1779-high-band-b02-schematic.pdf](url) mentions 
The following Pins:

- SW_CTL
- PC5
- PC3

I cannot see SW_CTL in your config. Is this referenced by somthing else?

**Comment by mgergos** [comment]
If I recall correctly, SW_RF =  PC4.It's exactly the same as the Nucleo board.There's no reference, just trial and mostly error.M.
-------- Original message --------From: Jeremy ***@***.***> Date: 30/10/24  7:16 am  (GMT+10:00) To: mgergos/B-WL5M-SUBG1 ***@***.***> Cc: Subscribed ***@***.***> Subject: [mgergos/B-WL5M-SUBG1] Question  (Issue #1) 
Hi
I am pulling my hair out trying to get a B-WL5M-SUBG1 working with ardunio and found your post and this Git hub post.
Quesiton:
Where did you find the reference to  PC3, PC4, PC5 for control of the internal RF Switch ? I am looking at the datasheet and I see PC5 and PC3 mentioned. They don't appear in the datasheet for the actuall MCU.
Did you get this fully working?
Thanks

**Comment by mgergos** [comment]
> Hi
> 
> I am pulling my hair out trying to get a B-WL5M-SUBG1 working with ardunio and found your post and this Git hub post.
> 
> Quesiton:
> 
> Where did you find the reference to PC3, PC4, PC5 for control of the internal RF Switch ? I am looking at the datasheet and I see PC5 and PC3 mentioned. They don't appear in the datasheet for the actuall MCU.
> 
> Did you get this fully working?
> 
> Sorry I also see a note in the code
> 
> ` __HAL_RCC_LSEDRIVE_CONFIG(RCC_LSEDRIVE_HIGH);`
> 
> Where did you find this in the datasheet? I think am being dumb but i cannot see it. The datasheet seems to be really lacking much description of how the radio is connected.
> 
> This is the one I have been attempting to use `https://www.st.com/resource/en/datasheet/stm32wl5moc.pdf`
> 
> Thanks

Page 5, Section 3.3 Clocks

**Comment by mgergos** [comment]
It's also worth noting that MXCube will not set LSE Drive as per the MOC datasheet. Nor does it set HSE to HSEBYPPWR if using the High speed osc. Just sets it to HSEON which doesn't work!

**Comment by fabltd** [comment]
Do you have any example code as I am unable to get this to work.

What LoRaWAN lib did you use ?
